### ISSUE TITLE
 'apt-get update' complains about a weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by chudler** [collectd/collectd-ci#19]
In recent releases of Debian and Ubuntu,  the apt tools warn about repositories using SHA1. Around this time next year, the tools will stop accepting packages from repositories signed with those.

Please consider updating your GPG settings to use a newer hash function. See https://askubuntu.com/questions/750133/how-can-i-fix-w-the-repository-is-insufficiently-signed-by-the-key, and https://wiki.debian.org/Teams/Apt/Sha1Removal). This will allow the official collectd repositories to work with future Debian-based systems.

To reproduce this issue, use https://pkg.ci.collectd.org/deb/ in a apt sources line along with Ubuntu 16.04 or a recent Debian stable/testing/unstable, and execute, e.g., "apt-get update".

Below is the actual error message generated by "apt update" on 16.04.1:

W: https://pkg.ci.collectd.org/deb/dists/xenial/Release.gpg: Signature by key F806817DC3F5EA417F9FA2963994D24FB8543576  uses weak digest algorithm (SHA1)

Thanks for looking into this.

**Comment by mfournier** [comment]
Thanks for the heads up @chudler !

If I recall, using sha1 was a compromise needed to support old EL5. But as another issue forced us to disable cryptographic signing for this distro anyways (be132ef), I believe nothing blocks us from updating the key to something more future-proof.

So the question now is: what key size, format and algo is the common denominator between all the distros we build packages for (excluding EL5) ?

**Comment by octo** [comment]
I'm not up-to-date with PGP, but with TLS the current de-facto standard is 2048bit RSA keys and SHA-256 for integrity.

HTH, —octo

**Comment by jplock** [comment]
Any update on this?

**Comment by jplock** [comment]
Any update on this?
