### ISSUE TITLE
CI on Solaris

### ISSUE THREAD

**Issue by dago** [collectd/collectd-ci#20]
Hi Marc,

we have buildbot as CI system on Solaris for collectd:
  https://buildfarm.opencsw.org/buildbot/waterfall?category=collectd
It would also be possible to include a Jenkins client on the buildfarm if that helps.
Otherwise would it be possible to include the link to our CI on the list of systems?

**Comment by octo** [comment]
Hi @dago, thanks for looking into this! I believe this issue can be resolved?

Best regards,
—octo

**Comment by dago** [comment]
Yes, I guess the buildbot integration works sufficiently good. If you have suggestions on enhancements just let me know.

Best regards -- Dago
